# Generated by Django 4.2.5 on 2023-09-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=30, unique=True, verbose_name='Ticket Number')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('state', models.CharField(max_length=30, verbose_name='State')),
                ('priority', models.CharField(max_length=30, verbose_name='Priority')),
                ('group', models.CharField(max_length=30, verbose_name='Group')),
                ('owner', models.CharField(max_length=30, verbose_name='Owner')),
                ('customer', models.CharField(max_length=30, verbose_name='Customer')),
                ('channel', models.CharField(max_length=30, verbose_name='Create Channel')),
                ('sender', models.CharField(max_length=30, verbose_name='Sender')),
                ('tags', models.CharField(max_length=300, verbose_name='Tags')),
                ('created_at', models.DateTimeField(verbose_name='Created At')),
                ('closed_at', models.DateTimeField(verbose_name='Closed At')),
                ('duration', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Problem',
                'verbose_name_plural': 'Problems',
                'db_table': 'problems',
            },
        ),
    ]
