# Generated by Django 4.2.5 on 2023-09-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('tag', models.CharField(max_length=30, verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Reason',
                'verbose_name_plural': 'Reasons',
                'db_table': 'reasons',
            },
        ),
    ]
